/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map_h_INCLUDE
#define __map_h_INCLUDE

#define background_mapWidth 32
#define background_mapHeight 32
#define background_mapBank 0

#define background_map background_mapPLN0
extern const unsigned char background_mapPLN0[];
extern const unsigned char background_mapPLN1[];

#endif

/* End of MAP.H */
