/*

 BATTLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __battlemap_h_INCLUDE
#define __battlemap_h_INCLUDE

#define background_map_battleWidth 32
#define background_map_battleHeight 32
#define background_map_battleBank 0

#define background_map_battle background_map_battlePLN0
extern const unsigned char background_map_battlePLN0[];
extern const unsigned char background_map_battlePLN1[];

#endif

/* End of BATTLEMAP.H */
