/*

 TITLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __title_h_INCLUDE
#define __title_h_INCLUDE

#define title_screenWidth 20
#define title_screenHeight 18
#define title_screenBank 0

#define title_screen title_screenPLN0
extern const unsigned char title_screenPLN0[];
extern const unsigned char title_screenPLN1[];

#endif

/* End of TITLE.H */
